/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardWebsitesRouteImport } from './routes/dashboard.websites'
import { Route as DashboardTicketsRouteImport } from './routes/dashboard.tickets'
import { Route as DashboardSubscriptionsRouteImport } from './routes/dashboard.subscriptions'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardScrapingStatusRouteImport } from './routes/dashboard.scraping-status'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardDownloadsRouteImport } from './routes/dashboard.downloads'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin-settings'
import { Route as DashboardSubscriptionsSuccessRouteImport } from './routes/dashboard.subscriptions.success'
import { Route as DashboardSubscriptionsCheckoutRouteImport } from './routes/dashboard.subscriptions.checkout'
import { Route as DashboardSubscriptionsCancelRouteImport } from './routes/dashboard.subscriptions.cancel'
import { Route as DashboardInvoicesInvoiceIdRouteImport } from './routes/dashboard.invoices.$invoiceId'
import { Route as DashboardDownloadsCustomizeRouteImport } from './routes/dashboard.downloads_.customize'
import { Route as DashboardAdminSubscriptionsRouteImport } from './routes/dashboard.admin.subscriptions'
import { Route as DashboardAdminInvoicesRouteImport } from './routes/dashboard.admin.invoices'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebsitesRoute = DashboardWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTicketsRoute = DashboardTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsRoute = DashboardSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScrapingStatusRoute = DashboardScrapingStatusRouteImport.update({
  id: '/scraping-status',
  path: '/scraping-status',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDownloadsRoute = DashboardDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSubscriptionsSuccessRoute =
  DashboardSubscriptionsSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => DashboardSubscriptionsRoute,
  } as any)
const DashboardSubscriptionsCheckoutRoute =
  DashboardSubscriptionsCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => DashboardSubscriptionsRoute,
  } as any)
const DashboardSubscriptionsCancelRoute =
  DashboardSubscriptionsCancelRouteImport.update({
    id: '/cancel',
    path: '/cancel',
    getParentRoute: () => DashboardSubscriptionsRoute,
  } as any)
const DashboardInvoicesInvoiceIdRoute =
  DashboardInvoicesInvoiceIdRouteImport.update({
    id: '/$invoiceId',
    path: '/$invoiceId',
    getParentRoute: () => DashboardInvoicesRoute,
  } as any)
const DashboardDownloadsCustomizeRoute =
  DashboardDownloadsCustomizeRouteImport.update({
    id: '/downloads_/customize',
    path: '/downloads/customize',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminSubscriptionsRoute =
  DashboardAdminSubscriptionsRouteImport.update({
    id: '/admin/subscriptions',
    path: '/admin/subscriptions',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAdminInvoicesRoute = DashboardAdminInvoicesRouteImport.update({
  id: '/admin/invoices',
  path: '/admin/invoices',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard/admin-settings': typeof DashboardAdminSettingsRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/scraping-status': typeof DashboardScrapingStatusRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRouteWithChildren
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/websites': typeof DashboardWebsitesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/invoices': typeof DashboardAdminInvoicesRoute
  '/dashboard/admin/subscriptions': typeof DashboardAdminSubscriptionsRoute
  '/dashboard/downloads/customize': typeof DashboardDownloadsCustomizeRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/subscriptions/cancel': typeof DashboardSubscriptionsCancelRoute
  '/dashboard/subscriptions/checkout': typeof DashboardSubscriptionsCheckoutRoute
  '/dashboard/subscriptions/success': typeof DashboardSubscriptionsSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard/admin-settings': typeof DashboardAdminSettingsRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/scraping-status': typeof DashboardScrapingStatusRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRouteWithChildren
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/websites': typeof DashboardWebsitesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/invoices': typeof DashboardAdminInvoicesRoute
  '/dashboard/admin/subscriptions': typeof DashboardAdminSubscriptionsRoute
  '/dashboard/downloads/customize': typeof DashboardDownloadsCustomizeRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/subscriptions/cancel': typeof DashboardSubscriptionsCancelRoute
  '/dashboard/subscriptions/checkout': typeof DashboardSubscriptionsCheckoutRoute
  '/dashboard/subscriptions/success': typeof DashboardSubscriptionsSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/dashboard/admin-settings': typeof DashboardAdminSettingsRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRouteWithChildren
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/scraping-status': typeof DashboardScrapingStatusRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/subscriptions': typeof DashboardSubscriptionsRouteWithChildren
  '/dashboard/tickets': typeof DashboardTicketsRoute
  '/dashboard/websites': typeof DashboardWebsitesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/invoices': typeof DashboardAdminInvoicesRoute
  '/dashboard/admin/subscriptions': typeof DashboardAdminSubscriptionsRoute
  '/dashboard/downloads_/customize': typeof DashboardDownloadsCustomizeRoute
  '/dashboard/invoices/$invoiceId': typeof DashboardInvoicesInvoiceIdRoute
  '/dashboard/subscriptions/cancel': typeof DashboardSubscriptionsCancelRoute
  '/dashboard/subscriptions/checkout': typeof DashboardSubscriptionsCheckoutRoute
  '/dashboard/subscriptions/success': typeof DashboardSubscriptionsSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/complete-profile'
    | '/cookie-policy'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard/admin-settings'
    | '/dashboard/downloads'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/products'
    | '/dashboard/scraping-status'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/tickets'
    | '/dashboard/websites'
    | '/dashboard/'
    | '/dashboard/admin/invoices'
    | '/dashboard/admin/subscriptions'
    | '/dashboard/downloads/customize'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/subscriptions/cancel'
    | '/dashboard/subscriptions/checkout'
    | '/dashboard/subscriptions/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/complete-profile'
    | '/cookie-policy'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard/admin-settings'
    | '/dashboard/downloads'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/products'
    | '/dashboard/scraping-status'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/tickets'
    | '/dashboard/websites'
    | '/dashboard'
    | '/dashboard/admin/invoices'
    | '/dashboard/admin/subscriptions'
    | '/dashboard/downloads/customize'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/subscriptions/cancel'
    | '/dashboard/subscriptions/checkout'
    | '/dashboard/subscriptions/success'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/complete-profile'
    | '/cookie-policy'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/terms'
    | '/dashboard/admin-settings'
    | '/dashboard/downloads'
    | '/dashboard/invoices'
    | '/dashboard/notifications'
    | '/dashboard/products'
    | '/dashboard/scraping-status'
    | '/dashboard/settings'
    | '/dashboard/subscriptions'
    | '/dashboard/tickets'
    | '/dashboard/websites'
    | '/dashboard/'
    | '/dashboard/admin/invoices'
    | '/dashboard/admin/subscriptions'
    | '/dashboard/downloads_/customize'
    | '/dashboard/invoices/$invoiceId'
    | '/dashboard/subscriptions/cancel'
    | '/dashboard/subscriptions/checkout'
    | '/dashboard/subscriptions/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/websites': {
      id: '/dashboard/websites'
      path: '/websites'
      fullPath: '/dashboard/websites'
      preLoaderRoute: typeof DashboardWebsitesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tickets': {
      id: '/dashboard/tickets'
      path: '/tickets'
      fullPath: '/dashboard/tickets'
      preLoaderRoute: typeof DashboardTicketsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions': {
      id: '/dashboard/subscriptions'
      path: '/subscriptions'
      fullPath: '/dashboard/subscriptions'
      preLoaderRoute: typeof DashboardSubscriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scraping-status': {
      id: '/dashboard/scraping-status'
      path: '/scraping-status'
      fullPath: '/dashboard/scraping-status'
      preLoaderRoute: typeof DashboardScrapingStatusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/downloads': {
      id: '/dashboard/downloads'
      path: '/downloads'
      fullPath: '/dashboard/downloads'
      preLoaderRoute: typeof DashboardDownloadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin-settings': {
      id: '/dashboard/admin-settings'
      path: '/admin-settings'
      fullPath: '/dashboard/admin-settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/subscriptions/success': {
      id: '/dashboard/subscriptions/success'
      path: '/success'
      fullPath: '/dashboard/subscriptions/success'
      preLoaderRoute: typeof DashboardSubscriptionsSuccessRouteImport
      parentRoute: typeof DashboardSubscriptionsRoute
    }
    '/dashboard/subscriptions/checkout': {
      id: '/dashboard/subscriptions/checkout'
      path: '/checkout'
      fullPath: '/dashboard/subscriptions/checkout'
      preLoaderRoute: typeof DashboardSubscriptionsCheckoutRouteImport
      parentRoute: typeof DashboardSubscriptionsRoute
    }
    '/dashboard/subscriptions/cancel': {
      id: '/dashboard/subscriptions/cancel'
      path: '/cancel'
      fullPath: '/dashboard/subscriptions/cancel'
      preLoaderRoute: typeof DashboardSubscriptionsCancelRouteImport
      parentRoute: typeof DashboardSubscriptionsRoute
    }
    '/dashboard/invoices/$invoiceId': {
      id: '/dashboard/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/dashboard/invoices/$invoiceId'
      preLoaderRoute: typeof DashboardInvoicesInvoiceIdRouteImport
      parentRoute: typeof DashboardInvoicesRoute
    }
    '/dashboard/downloads_/customize': {
      id: '/dashboard/downloads_/customize'
      path: '/downloads/customize'
      fullPath: '/dashboard/downloads/customize'
      preLoaderRoute: typeof DashboardDownloadsCustomizeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/subscriptions': {
      id: '/dashboard/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/dashboard/admin/subscriptions'
      preLoaderRoute: typeof DashboardAdminSubscriptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin/invoices': {
      id: '/dashboard/admin/invoices'
      path: '/admin/invoices'
      fullPath: '/dashboard/admin/invoices'
      preLoaderRoute: typeof DashboardAdminInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardInvoicesRouteChildren {
  DashboardInvoicesInvoiceIdRoute: typeof DashboardInvoicesInvoiceIdRoute
}

const DashboardInvoicesRouteChildren: DashboardInvoicesRouteChildren = {
  DashboardInvoicesInvoiceIdRoute: DashboardInvoicesInvoiceIdRoute,
}

const DashboardInvoicesRouteWithChildren =
  DashboardInvoicesRoute._addFileChildren(DashboardInvoicesRouteChildren)

interface DashboardSubscriptionsRouteChildren {
  DashboardSubscriptionsCancelRoute: typeof DashboardSubscriptionsCancelRoute
  DashboardSubscriptionsCheckoutRoute: typeof DashboardSubscriptionsCheckoutRoute
  DashboardSubscriptionsSuccessRoute: typeof DashboardSubscriptionsSuccessRoute
}

const DashboardSubscriptionsRouteChildren: DashboardSubscriptionsRouteChildren =
  {
    DashboardSubscriptionsCancelRoute: DashboardSubscriptionsCancelRoute,
    DashboardSubscriptionsCheckoutRoute: DashboardSubscriptionsCheckoutRoute,
    DashboardSubscriptionsSuccessRoute: DashboardSubscriptionsSuccessRoute,
  }

const DashboardSubscriptionsRouteWithChildren =
  DashboardSubscriptionsRoute._addFileChildren(
    DashboardSubscriptionsRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardDownloadsRoute: typeof DashboardDownloadsRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRouteWithChildren
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardScrapingStatusRoute: typeof DashboardScrapingStatusRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSubscriptionsRoute: typeof DashboardSubscriptionsRouteWithChildren
  DashboardTicketsRoute: typeof DashboardTicketsRoute
  DashboardWebsitesRoute: typeof DashboardWebsitesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminInvoicesRoute: typeof DashboardAdminInvoicesRoute
  DashboardAdminSubscriptionsRoute: typeof DashboardAdminSubscriptionsRoute
  DashboardDownloadsCustomizeRoute: typeof DashboardDownloadsCustomizeRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardDownloadsRoute: DashboardDownloadsRoute,
  DashboardInvoicesRoute: DashboardInvoicesRouteWithChildren,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardScrapingStatusRoute: DashboardScrapingStatusRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSubscriptionsRoute: DashboardSubscriptionsRouteWithChildren,
  DashboardTicketsRoute: DashboardTicketsRoute,
  DashboardWebsitesRoute: DashboardWebsitesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminInvoicesRoute: DashboardAdminInvoicesRoute,
  DashboardAdminSubscriptionsRoute: DashboardAdminSubscriptionsRoute,
  DashboardDownloadsCustomizeRoute: DashboardDownloadsCustomizeRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
